# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

workspace 'multipeer-quiz-game'

target 'multipeer-quiz-game' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for multipeer-quiz-game
  pod 'Firebase/Core'
end
